name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          platform: linux
          arch: x64
        - os: ubuntu-latest
          platform: android
          arch: x64
          flags: --android-ndk 26.1.10909125 --android-api 34
        - os: ubuntu-latest
          platform: android
          arch: ia32
          flags: --android-ndk 26.1.10909125 --android-api 34
        - os: ubuntu-latest
          platform: android
          arch: arm64
          flags: --android-ndk 26.1.10909125 --android-api 34
        - os: ubuntu-latest
          platform: android
          arch: arm
          flags: --android-ndk 26.1.10909125 --android-api 34
        - os: macos-latest
          platform: darwin
          arch: arm64
        - os: windows-latest
          platform: win32
          arch: x64
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.platform }}-${{ matrix.arch }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - run: npm install -g bare-dev
    - run: bare-dev configure --debug --platform ${{ matrix.platform }} --arch ${{ matrix.arch }} ${{ matrix.flags }}
    - run: bare-dev build --debug
    - run: bare-dev test --debug
      if: ${{ matrix.platform == 'linux' || matrix.platform == 'darwin' || matrix.platform == 'win32' }}
